admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: dns:///localhost:30080
  insecure: true
  insecureSkipVerify: true

# Web console configuration
console:
  endpoint: http://localhost:30081